version: '3'
services:
  nginx:
    image: jchflask/web
    build:
      context: ./docker/proxy
    ports:
        - 80:80
    volumes:
      - ./dist:/app
  flask:
    image: jchflask/flask
    build:
      context: ./docker/flask
    ports:
        - 8001:8001
    volumes:
      - ./api:/api
