version: '3'
services:
  nginx:
    image: jchflask/proxy
    build:
      context: ./docker/proxy
    ports:
        - 80:80
    volumes:
      - ./:/app
      - /home/jhardy/projects/johnchardy.com/code/plugindev:/plugindev
      - ./docker/nginx/conf/conf.d:/etc/nginx/conf.d
